"""Use timezone-aware enrollment timestamps

Revision ID: 03d3cd17fcbc
Revises: 7d99c926e188
Create Date: 2026-09-14 14:09:05.543313

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "03d3cd17fcbc"
down_revision: str | Sequence[str] | None = "7d99c926e188"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "enrollments",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        postgresql_using="created_at AT TIME ZONE 'UTC'",
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        server_default=sa.func.now(),
    )
    op.alter_column(
        "enrollments",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        postgresql_using="updated_at AT TIME ZONE 'UTC'",
        existing_nullable=False,
        existing_server_default=sa.text("timezone('utc'::text, now())"),
        server_default=sa.func.now(),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "enrollments",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        postgresql_using="updated_at AT TIME ZONE 'UTC'",
        existing_nullable=False,
        existing_server_default=sa.func.now(),
        server_default=sa.text("timezone('utc'::text, now())"),
    )
    op.alter_column(
        "enrollments",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        postgresql_using="created_at AT TIME ZONE 'UTC'",
        existing_nullable=False,
        existing_server_default=sa.func.now(),
        server_default=sa.text("timezone('utc'::text, now())"),
    )
    # ### end Alembic commands ###
