"""Align database defaults and course description

Revision ID: 916c146c72f6
Revises: 03d3cd17fcbc
Create Date: 2026-09-17 14:47:42.221302

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "916c146c72f6"
down_revision: str | Sequence[str] | None = "03d3cd17fcbc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "courses", "description", existing_type=sa.VARCHAR(length=1000), nullable=True
    )
    op.alter_column(
        "courses",
        "capacity",
        existing_type=sa.INTEGER(),
        server_default="100",
        existing_nullable=False,
    )
    op.alter_column(
        "courses",
        "level",
        existing_type=postgresql.ENUM(
            "beginner", "intermediate", "advanced", name="courselevel"
        ),
        server_default="beginner",
        existing_nullable=False,
    )
    op.alter_column(
        "courses",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=sa.text("true"),
        existing_nullable=False,
    )
    op.alter_column(
        "enrollments",
        "status",
        existing_type=postgresql.ENUM(
            "active", "cancelled", "completed", name="status"
        ),
        server_default="active",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "enrollments",
        "status",
        existing_type=postgresql.ENUM(
            "active", "cancelled", "completed", name="status"
        ),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "courses",
        "is_active",
        existing_type=sa.BOOLEAN(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "courses",
        "level",
        existing_type=postgresql.ENUM(
            "beginner", "intermediate", "advanced", name="courselevel"
        ),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "courses",
        "capacity",
        existing_type=sa.INTEGER(),
        server_default=None,
        existing_nullable=False,
    )

    courses = sa.table(
        "courses",
        sa.column("description", sa.String()),
    )
    op.execute(
        sa.update(courses)
        .filter(courses.c.description.is_(None))
        .values(description="Description unavailable")
    )
    op.alter_column(
        "courses", "description", existing_type=sa.VARCHAR(length=1000), nullable=False
    )
    # ### end Alembic commands ###
