"""Create initial tables

Revision ID: e7c74ae76292
Revises: 
Create Date: 2026-08-29 14:22:41.417820

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e7c74ae76292'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('teacher', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('level', sa.Enum('beginner', 'intermediate', 'advanced', name='courselevel'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.CheckConstraint('capacity >= 1 and capacity <= 500', name='check_capacity'),
    sa.CheckConstraint('char_length(description) >= 10', name='check_description_length'),
    sa.CheckConstraint('char_length(name) >= 3', name='check_name_length'),
    sa.CheckConstraint('char_length(teacher) >= 3', name='check_teacher_length'),
    sa.CheckConstraint('price >= 0', name='check_price'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('skills', sa.ARRAY(sa.Enum('python', 'rust', 'c', 'go', 'java', 'fastapi', 'postgresql', 'docker', 'git', 'sqlalchemy', 'redis', 'kubernetes', name='student_skill')), server_default=sa.text("'{}'::student_skill[]"), nullable=False),
    sa.CheckConstraint('age >= 16 AND age <= 100', name='check_age'),
    sa.CheckConstraint('char_length(full_name) >= 3', name='check_name_length'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_check_email')
    )
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('active', 'cancelled', 'completed', name='status'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text("TIMEZONE('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_enrollments_active_student_course', 'enrollments', ['student_id', 'course_id'], unique=True, postgresql_where=sa.text("status = 'active'"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_enrollments_active_student_course', table_name='enrollments', postgresql_where=sa.text("status = 'active'"))
    op.drop_table('enrollments')
    op.drop_table('students')
    op.drop_table('courses')
    # ### end Alembic commands ###
